app1/urls.py
from django.urls import path
from . import views

app_name = 'app1'

urlpatterns = [
    path('help/', views.help, name='help'),
    path('sp/', views.sp, name='sp'),
    path('calculadora/', views.calculadora, name='calculadora'),
    path('acesso/', views.acesso, name='acesso'),
    path('form/', views.form_name, name='form'),
    path('modelform/', views.users, name='modelform'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from app1 import views

app_name = 'app1'

urlpatterns = [
    path('', views.index, name='index'),
    path('app1/', include('app1.urls')),
    path('admin/', admin.site.urls, name='admin'),
]

app1/models.py
from django.db import models


# Create your models here.
class Topico(models.Model):
    nome = models.CharField(max_length=264, unique=True)#chave primaria


    def __str__(self):
        return self.nome                                     #padrao de str para mostrar no admin

class Webpage(models.Model):                                     #classes de python representando modelos de dados
    topico = models.ForeignKey(Topico, on_delete=models.CASCADE) #Chave estrangeira - on_delete cascade para apagar tbm os acessos
    nome = models.CharField(max_length=264, unique=True)         #Um campo string, para campos texto de tamanhos pequeno e médio e unico
    url = models.URLField(unique=True)                           #um CharField com validador de URL e unico

    def __str__(self):
        return self.nome

class RegistroAcesso(models.Model):
    pagina = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    data = models.DateField()                                    #uma data em formato padrao

    def __str__(self):
        return str(self.data)

class Model(models.Model):
    nome = models.CharField(max_length=264, unique=True)         #chave primaria

    def __str__(self):
        return self.nome                                         #padrao de str para mostrar no admin

class DadosForm(models.Model):
    nome = models.CharField(max_length=264, unique=True)         #chave primaria
    email = models.EmailField(max_length=264, unique=True)
    texto = models.CharField(max_length=264, unique=True)
    endereco = models.CharField(max_length=264, unique=True)
    cidade = models.CharField(max_length=264, unique=True)


    def __str__(self):
        return self.nome                                         #padrao de str para mostrar no admin

app1/forms.py
from django import forms
from app1.models import Topico, DadosForm


class FormName(forms.Form):
    nome = forms.CharField(max_length=100)
    email = forms.EmailField()
    texto = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput)

    def clean_botcatcher(self):
        botcatcher = self.cleaned_data['botcatcher']
        if len(botcatcher) > 0:
            raise forms.ValidationError("GOTCHA BOT!")
        return botcatcher

class ModelForm1(forms.ModelForm):
    class Meta:
        model = DadosForm
        fields = "__all__"

app1/views.py
from django.http import HttpResponse
from django.shortcuts import render
from app1.models import RegistroAcesso
from .forms import FormName, ModelForm1


# Create your views here.
def index(request):
    return render(request, 'app1/index.html')

def help(request):
    return render(request, 'app1/help.html')

def sp(request):
    return render(request, 'app1/sp.html')

def calculadora(request):
    return render(request, 'app1/calculadora.html')

def acesso(request):
    lista_paginas = RegistroAcesso.objects.order_by('data')
    dict_lista2 = {"lista_acessos": lista_paginas}
    return render(request, 'app1/acesso.html', dict_lista2)

def formulario(request):
    return render(request, 'app1/formulario.html')

def form_name(request):
    form = FormName()

    if request.method == 'POST':
        form = FormName(request.POST)

        if form.is_valid():
            print("Os campos estão corretos")
            print("Nome: " + form.cleaned_data['nome'])
            print("Email: " + form.cleaned_data['email'])
            print("Texto: " + form.cleaned_data['texto'])

    return render(request, 'app1/form.html', {"form": form})


def topico_modelform(request):
    form = ModelForm1()
    return render(request, 'app1/modelform1.html', context={'modelform1': form})

def users(request):
    form = ModelForm1()

    if request.method == 'POST':
        form = ModelForm1(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('ERRO FORM INVALID')

    return render(request, 'app1/modelform1.html', {'form': form})

app1/templates/app1/acesso.html
<!DOCTYPE html>
{% extends 'app1/index.html' %}
{% load static %}

    <html lang="pt-BR">
    {% block conteudo %}
        <head>
            <meta charset="UTF-8">
            <link rel="stylesheet" type="text/css" href="{% static "css/acesso.css" %}">
            <title>Acessos</title>
        </head>
        <body>
            <h2>Aqui estão os registros de acesso:</h2>
            <div class="djangtwo">
                {% if lista_acessos %}
                    <table>
                        <thead>
                            <th>Nome da Página</th>
                            <th>Data de Acesso</th>
                        </thead>
                        {% for acesso in lista_acessos %}
                            <tr>
                                <td>{{ acesso.pagina|title}}</td>
                                <td>{{ acesso.data|date:"D d M Y" }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <p>Sem registros. Tabela não criada.</p>
                {% endif %}
            </div>
        </body>
    {% endblock %}
    </html>

app1/templates/app1/calculadora.html
<!DOCTYPE html>
{% extends 'app1/index.html' %}
{% load static %}

    <html lang="pt-BR">
        {% block conteudo %}
        <head>
            <meta charset="UTF-8">
	        <title>Minha Calculadora</title>
	        <link rel="stylesheet" type="text/css" href="{% static "css/calculadora.css" %}">
            <script src="{% static "js/calculadora.js" %}"></script>
        </head>
        <body>
            <div id="calcInteira">
                	<p id="visor">0</p>
	                <table>
	                    <tr>
	                        <td><button onclick="cleear()">C</button></td>
	                        <td><button onclick="btPonto()">.</button></td>
	                        <td><button id="bdivisao" onclick="operador(this.id)">/</button></td>
	                    </tr>
	                    <tr>
	                    <td><button id="bsoma" onclick="operador(this.id)">+</button></td>
	                    <td><button id="bsubtracao" onclick="operador(this.id)">-</button></td>
	                    <td><button id="bmultiplicacao" onclick="operador(this.id)">*</button></td>
	                    </tr>
	                    <tr>
	                    <td><button id="b7" onclick="botao_numero(this.id)">7</button></td>
	                    <td><button id="b8" onclick="botao_numero(this.id)">8</button></td>
	                    <td><button id="b9" onclick="botao_numero(this.id)">9</button></td>
	                    </tr>
	                    <tr>
	                    <td><button id="b4" onclick="botao_numero(this.id)">4</button></td>
	                    <td><button id="b5" onclick="botao_numero(this.id)">5</button></td>
	                    <td><button id="b6" onclick="botao_numero(this.id)">6</button></td>
	                    </tr>
	                    <tr>
	                    <td><button id="b1" onclick="botao_numero(this.id)">1</button></td>
	                    <td><button id="b2" onclick="botao_numero(this.id)">2</button></td>
	                    <td><button id="b3" onclick="botao_numero(this.id)">3</button></td>
	                    </tr>
	                    <tr>
	                    <td><button onclick="positivoNegativo()">+/-</button></td>
	                    <td><button id="b0" onclick="botao_numero(this.id)">0</button></td>
	                    <td><button onclick="resultado()">=</button></td>
	                    </tr>
                    </table>
            </div>
        </body>
        {% endblock %}
    </html>

app1/templates/app1/form.html
<!DOCTYPE html>
{% extends "app1/index.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% load static %}

    <html lang="pt-BR">
      {% block conteudo %}
        <body>
            <div class="pagform">
                <head>
                    <meta charset="UTF-8">
                    <title>Formulario</title>
                    <link rel="stylesheet" type="text/css" href="{% static "css/form.css" %}">
                </head>
                    <h1>Vamos preencher o form</h1>
                    <form method="POST" class="grupo">
                        {{ form|crispy }}
                        {% csrf_token %}
                        <input type="submit" class="btn btn-primary" value="Submit">
                    </form>
            </div>
        </body>
      {% endblock %}
    </html>

app1/templates/app1/help.html
<!DOCTYPE html>
{% extends 'app1/index.html' %}
{% load static %}

    <html lang="pt-BR">
        <head>
            <meta charset="UTF-8">
            <title>title</title>
        </head>
        <body>
            {% block conteudo %}
                <h1>olá, area de ajuda</h1>
                {{  variavel }}
            {% endblock %}
        </body>
    </html>

app1/templates/app1/index.html
<!DOCTYPE html>
{% load static %}

    <html lang="pt-BR">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <link rel="stylesheet" type="text/css" href="{% static "css/index.css" %}">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
            <title>Programação Web II</title>
        </head>
        <body>
            {% block body %}
                <div class="pag">
                    <div class="menu">
                        <nav>
                            <a href="{% url 'index' %}">Inicio</a>
                            <a href="{% url 'app1:sp' %}">São Paulo</a>
                            <a href="{% url 'app1:calculadora' %}">Calculadora</a>
                            <a href="{% url 'admin:index' %}">Painel Admin</a>
                            <a href="{% url 'app1:acesso' %}">Registro de Acesso</a>
                            <a href="{% url 'app1:modelform' %}">Formulario</a>
                            <a href="{% url 'app1:form' %}">Form</a>
                            <a href="{% url 'app1:help' %}">Ajuda</a>
                        </nav>
                    </div>
                    {% block conteudosp %}
                        <div class="conteudo">
                            {% block conteudo %}
                                <div class="imagem-Django"></div>
                                <p class ="estilo">Programando em Django</p>
                        </div>
                        {% endblock %}
                        <div class="rodape">
                            {% block rodape %}
                                <p class="p-rodape">Página HTML desenvolvido por Rogério Dagnon®</p>
                            {% endblock %}
                        </div>
                    {% endblock %}
                </div>
            {% endblock %}
                        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        </body>
    </html>

app1/templates/app1/modelform1.html
<!DOCTYPE html>
{% extends "app1/index.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% load static %}

    <html lang="pt-BR">
        {% block conteudo %}
        <body>
            <div class="container">
                <head>
                    <meta charset="UTF-8">
                    <title>Form</title>
                    <link rel="stylesheet" type="text/css" href="{% static "css/modelform1.css" %}">
                </head>
                    <h1>Vamos preencher o formulario!</h1>
                    <form method="POST" class="grupo1">
                        {{ form|crispy }}
                        {% csrf_token %}
                        <input type="submit" class="btn btn-primary" value="Submit">
                    </form>
            </div>
        </body>
        {% endblock %}
    </html>

app1/templates/app1/sp.html
<!DOCTYPE html>
{% extends 'app1/index.html' %}
{% load static %}

    <html lang="pt-BR">
        {% block conteudosp %}
        <head>
            <meta charset="UTF-8">
            <title>São Paulo</title>
            <link rel="stylesheet" type="text/css" href="{% static "css/saopaulo.css" %}">
        </head>
        <body>
            <div class="conteiner">

                    <h1><a href="/">O que eu mais gosto em São Paulo</a></h1>
                    <div class="lugares">
                        <h2>Passear na Avenida Paulista</h2>
                        <img src="https://media-cdn.tripadvisor.com/media/photo-s/18/99/d8/ed/paulista.jpg" alt="Av. Paulista" >
                        <p>
                        Um dos principais centros financeiros da cidade, a avenida Paulista
                        também possui diversas opções de entretenimento. Endereço do Museu
                        de Arte de São Paulo, <em>MASP</em>, do Teatro Gazeta e muitos outros,
                        a região é de fácil acesso graças as diversas linhas de ônibus que
                        cruzam a avenida e a linha de metrô que passa por baixo dela.
                        </p>
                        <p>
                        A avenida paulista sempre é assunto. O que será que estão falando a respeito
                        no <a href="https://twitter.com/search?q=Avenida Paulista">Twitter.</a>
                        </p>
                    </div>
                    <div class="lugares">
                        <h2>Os bares da Vila Madalena</h2>
                        <img src="https://www.guiadasemana.com.br/contentFiles/image/opt_w840h0/2019juliana/lugares/vila-madalena/28060886-1719018988119237-4294555165498106193-o.jpg" alt="Vila Madalena">
                        <p>
                        Depois de um dia de trabalho, nada melhor do que um bom chopp, um
                        petisco e uma conversa em uma mesa de bar. Opções de sobra na região
                        das ruas Aspicuelta, Fradique Coutinho e Wisard.
                        </p>
                        <p>
                        Veja quais os melhores bares e restaurantes da região no
                        <a href="https://vejasp.abril.com.br/cidades/melhor-da-vila-madalena-restaurantes/">Guia da VEJA São Paulo.</a>
                        </p>
                    </div>
                    <div class="lugares">
                        <h2>O Parque Ibirapuera</h2>
                        <img src="https://abrilexame.files.wordpress.com/2019/03/parque-do-ibirapuera.gif" alt="Parque Ibirapuera">
                        <p>
                        Um dos cartões postais da cidade, o parque dispõe de mais de 1,5 km{^2}
                        de área verde, lagos artificiais e pistas de cooper e ciclismo. E se
                        isso não fosse o suficiente, o parque costuma ser palco de diversos
                        eventos culturais ao longo do ano.
                        </p>
                        <p>
                        Veja no
                        <a href="http://goo.gl/maps/HoH8">mapa</a>
                        como chegar ao parque.
                        </p>
                    </div>
            </div>
            <div class="lista">
                <h3>E existem muitos outros lugares interessantes na idade...</h3>
                <ol>
                    <li> O Mercado Municipal.</li>
                    <li> A Sala São Paulo.</li>
                    <li> Os estádios dos principais times de futebol da cidade.</li>
                    <li> Diversos museus, como o Memorial da América Latina, Museu da Língua Portuguesa e o Museu do Ipiranga.</li>
                    <li> E mais!</li>
                </ol>
            </div>
            <div class="rodape">
                <p>
                Página HTML desenvolvido por Rogério Dagnon®"
                </p>
            </div>
        </body>
        {% endblock %}
    </html>